config/routes.rb
Tracking::Application.routes.draw do

  get "daily_activities/new"

  root to: 'pages#home'
  
  # Refactored routes to make nearly all resourceful. 

  resources :employees
  resources :clients
  resources :codes
  resources :codelines
  resources :contracts
  resources :sessions, only:  [:new, :create, :destroy]
  
  
  match '/code_list',       to:     'codes#code_list' # Added this route for the autocomplete functionality.
  match '/client_list',     to:     'clients#client_list' # Added this route for the autocomplete functionality.
  match '/get_client_data', to:     'clients#get_client_data' # Added this route for the autocomplete functionality.
  match '/get_code_data',   to:     'codes#get_code_data' # Added this route for the autocomplete functionality.
  match '/employees/:id',   to:     'employees#show', :as => :employee
  match '/newemployee',     to:     'employees#new'
  match '/signin',          to:     'sessions#new'
  match '/signout',         to:     'sessions#destroy', via: :delete
  match '/home',            to:     'pages#home'
  match '/about',           to:     'pages#about'
  match '/contact',         to:     'pages#contact'
  match '/help',            to:     'pages#help'

end

app/models/contract.rb
# == Schema Information
#
# Table name: contracts
#
#  id         :integer         not null, primary key
#  authnum    :string(255)
#  st_date    :date
#  end_date   :date
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  client_id  :integer
#

class Contract < ActiveRecord::Base
  belongs_to :client, inverse_of: :contracts
  has_many :codelines
  has_many :codes, through: :codelines
  
  attr_accessible :authnum, :st_date, :end_date, :client_id, :clients, :client_attributes, :codelines, :codelines_attributes, :code_attributes
  
  accepts_nested_attributes_for :client
  accepts_nested_attributes_for :codelines, allow_destroy: true, :reject_if => lambda { |a| a[:units_alloc].blank? }
  
  # See codeline model for explanation of this pattern and how to utilize the associations.
  
  def client_attributes=(params)
    client_to_save = Client.find_or_create_by_name(params[:name])
    self.client = client_to_save
    client_to_save.birth_date = params[:birth_date]
    client_to_save.address1 = params[:address1]
    client_to_save.address2 = params[:address2]
    client_to_save.city = params[:city]
    client_to_save.state = params[:state]
    client_to_save.zip_code = params[:zip_code]
    client_to_save.medicare_num = params[:medicare_num]
    client_to_save.medicaid_num = params[:medicaid_num]
    client_to_save.member_num = params[:member_num]
    client_to_save.soc_sec_care_mgr = params[:soc_sec_care_mgr]
    client_to_save.sscm_ph = params[:sscm_ph]
    client_to_save.nurse_care_mgr = params[:nurse_care_mgr]
    client_to_save.ncm_ph = params[:ncm_ph]
    client_to_save.emer_contact = params[:emer_contact]
    client_to_save.ec_ph = params[:ec_ph]
    client_to_save.pri_care_phy = params[:pri_care_phy]
    client_to_save.pcp_ph = params[:pcp_ph]
    client_to_save.save
  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController

  # I moved most of the functionality to the contracts controller, given that it is the business
  # entity we are focused on. 

  def index
    @contracts = Contract.paginate(page: params[:page])
  end

  def show
    @contract = Contract.find(params[:id])
  end

  def new
    @show_remove = false
    @contract = Contract.new
    @contract.build_client
    @contract.codelines.build.build_code  # Check ActiveRecord Association documentation for build methods. This 
                                          # method chain builds the codeline first, then builds the code based on the
                                          # codeline object. The difference in .build vs build_ syntax is based on the
                                          # differing association type (belongs_to vs has_many)
  end

  def create
    @contract = Contract.new(params[:contract])
    if @contract.save
      flash[:success] = "New Contract has been saved"
      redirect_to @contract
    else
      @title = "You have some errors"
      render 'new'
    end
  end

  def edit
    @contract = Contract.find(params[:id])
  end

  def update
    @contract = Contract.find(params[:id])
    if @contract.update_attributes(params[:contract])
       flash[:success] = "Contract Profile updated"
       redirect_to @contract
    else
       render 'edit'
    end
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper

#  def link_to_add_fields(name, f, association, locals={})
#    new_object = f.object.class.reflect_on_association(association).klass.new
#    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
#      render(association.to_s.singularize + "_fields", locals.merge!(:f => builder))
#    end
#
#    link_to(name, "#", :class => "dynamic_add", 'data-association' => "#{associationi}", 'data-content' => "#{fields}")
#  end
end

app/views/contracts/_client_fields.html.haml
.field
  = client.label :name
  %br
  = client.text_field :name, data: {autocomplete_source: client_list_path}, :size => 15, :class => "ui-state-default"
.field
  = client.label :birth_date, "Birth Date"
  %br
  = client.text_field :birth_date, :size => 15, :class => "ui-state-default"
.field
  = client.label :address1, "Address1"
  %br
  = client.text_field :address1, :size => 15, :class => "ui-state-default"
.field
  = client.label :address2, "Address2"
  %br
  = client.text_field :address2, :size => 15, :class => "ui-state-default"
.field
  = client.label :city
  %br
  = client.text_field :city, :size => 15, :class => "ui-state-default"
.field
  = client.label :state, "State"
  %br
  = client.text_field :state, :size => 15, :class => "ui-state-default"
.field
  = client.label :zip_code, "Zip Code"
  %br
  = client.text_field :zip_code, :size => 15, :class => "ui-state-default"
.field
  = client.label :medicare_num
  %br
  = client.text_field :medicare_num, :size => 15, :class => "ui-state-default"
.field
  = client.label :medicaid_num
  %br
  = client.text_field :medicaid_num, :size => 15, :class => "ui-state-default"  
.field
  = client.label :member_num
  %br
  = client.text_field :member_num, :size => 15, :class => "ui-state-default"
.field
  = client.label :soc_sec_care_mgr
  %br
  = client.text_field :soc_sec_care_mgr, :size => 15, :class => "ui-state-default"
.field
  = client.label :sscm_ph
  %br
  = client.text_field :sscm_ph, :size => 15, :class => "ui-state-default"
.field
  = client.label :nurse_care_mgr
  %br
  = client.text_field :nurse_care_mgr, :size => 15, :class => "ui-state-default"
.field
  = client.label :ncm_ph
  %br
  = client.text_field :ncm_ph, :size => 15, :class => "ui-state-default"
.field
  = client.label :emer_contact
  %br
  = client.text_field :emer_contact, :size => 15, :class => "ui-state-default"
.field
  = client.label :ec_ph
  %br
  = client.text_field :ec_ph, :size => 15, :class => "ui-state-default"
.field
  = client.label :pri_care_phy
  %br
  = client.text_field :pri_care_phy, :size => 15, :class => "ui-state-default"
.field
  = client.label :pcp_ph
  %br
  = client.text_field :pcp_ph, :size => 15, :class => "ui-state-default"

app/views/contracts/_code_fields.html.haml
.field
  = code.label :code_name
  %br
  = code.text_field :code_name, data: {autocomplete_source: code_list_path}, :size => 10, :class => "ui-state-default"
.field
  = code.label :name, "Status"
  %br
  = code.text_field :status, :size => 10, :class => "ui-state-default"
.field
  = code.label :name, "Description"
  %br
  = code.text_field :description, :size => 25, :class => "ui-state-default"
    

app/views/contracts/_codeline_fields.html.haml
%fieldset
  - codeline.object.build_code
  = codeline.fields_for :code do |code|
    = render 'code_fields', code: code
  .field
    = codeline.label :name, "Units Alloc"
    %br/
    = codeline.text_field :units_alloc, :precision => 6, :scale => 2, :size => 10, :class => "ui-state-default"
    - if @show_remove
      = codeline.hidden_field :_destroy
      = link_to "remove", '#', class: "remove_fields"
    - else
      - @show_remove = true

app/views/contracts/_contract.html.haml
%li
  %span2
= link_to contract.authnum, contract

app/views/contracts/_contract_fields.html.haml
.field
  = contract.label :name, "AuthNum"
  %br/
  = contract.text_field  :authnum, :size => 10, :class => "ui-state-default"
.field
  = contract.label :name, "Start Date"
  %br/
  = contract.text_field  :st_date, :size => 12, :class => "ui-state-default"
.field
  = contract.label :name, "End Date"
  %br/
  = contract.text_field  :end_date, :size => 12, :class => "ui-state-default"

app/views/contracts/edit.html.haml
- provide(:title, 'Edit Contract')
%h2 Edit Contract
= form_for @contract do |contract|
  
  %fieldset
    %legend Enter Contract Details
    =render 'contract_fields', contract: contract
    
  %fieldset
    %legend Enter Client Details
    = contract.fields_for :client do |client|
      =render 'client_fields', client:  client
      
  %fieldset
    %legend Enter Billing Code Details
    = contract.fields_for :codelines do |codeline|
      = render 'codeline_fields', codeline: codeline
    = link_to_add_fields "Add Billing Code", contract, :codelines
    
  .actions
    = contract.submit "Update", class: 'save strong round'

app/views/contracts/index.html.haml
- provide(:title, 'All contracts')
%h4 All contracts
%br/
= will_paginate
%ul.contracts
  = render @contracts
%br/
%br/
= will_paginate

app/views/contracts/new.html.haml
- provide(:title, 'New Contract')
%h2 New Contract
= form_for @contract do |contract|
  
  %fieldset
    %legend Enter Contract Details
    =render 'contract_fields', contract: contract
    
  %fieldset
    %legend Enter Client Details
    = contract.fields_for :client do |client|
      =render 'client_fields', client: client

  %fieldset
    %legend Enter Billing Code Details
    = contract.fields_for :codelines do |codeline|
      =render 'codeline_fields', codeline: codeline
    = link_to_add_fields "Add Billing Code", contract, :codelines
    
  .actions
    = contract.submit "Save", class: 'save strong round'

app/views/contracts/show.html.haml
- provide(:title, "Contracts")
%h3
= @contract.authnum
= @contract.client.name
%span1
%ol
  - for codeline in @contract.codelines
    %li= codeline.code.code_name
    %li= codeline.code.status
    %li= codeline.code.description
    %li= codeline.units_alloc
%p