config/routes.rb
Tracking::Application.routes.draw do

  get "daily_activities/new"

  root to: 'pages#home'
  
  # Refactored routes to make nearly all resourceful. 

  resources :employees
  resources :clients
  resources :codes
  resources :codelines
  resources :contracts
  resources :sessions, only:  [:new, :create, :destroy]
  
  
  match '/code_list',       to:     'codes#code_list' # Added this route for the autocomplete functionality.
  match '/client_list',     to:     'clients#client_list' # Added this route for the autocomplete functionality.
  match '/get_client_data', to:     'clients#get_client_data' # Added this route for the autocomplete functionality.
  match '/get_code_data',   to:     'codes#get_code_data' # Added this route for the autocomplete functionality.
  match '/employees/:id',   to:     'employees#show', :as => :employee
  match '/newemployee',     to:     'employees#new'
  match '/signin',          to:     'sessions#new'
  match '/signout',         to:     'sessions#destroy', via: :delete
  match '/home',            to:     'pages#home'
  match '/about',           to:     'pages#about'
  match '/contact',         to:     'pages#contact'
  match '/help',            to:     'pages#help'

end

app/models/codeline.rb
# == Schema Information
#
# Table name: codelines
#
#  id          :integer         not null, primary key
#  contract_id :integer
#  code_id     :integer
#  client_id   :integer
#  units_alloc :decimal(6, 2)
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Codeline < ActiveRecord::Base
  belongs_to :code, inverse_of: :codelines
  belongs_to :contract
  
  attr_accessible :contract_id, :code_id, :units_alloc, :code_attributes
  
  accepts_nested_attributes_for :code, :allow_destroy => true, :reject_if => lambda { |a| a[:code_name].blank?
                                                                                          a[:status].blank?
                                                                                          a[:description].blank? }
                                                                                          
  validates(:code_id, :units_alloc, presence: true)
  validates(:units_alloc, numericality: true)
  
  # When you declare an association, you can then think of the code_attributes as an extension of the declaring model.
  # This setter method is like any other, expect it happens to accept an array of attributes. 
  # We call find_or_create to see if an existing record is in the database. If not, then we create one. We assign it
  # to self (in this case, the codeline object) and then go through the attributes and update them (in case they)
  # were changed during the contract creation process. Finally, we need to call save to make sure the insert statement
  # updates the database record and not just our in memory object.
  
  def code_attributes=(params)
    code_to_save = Code.find_or_create_by_code_name(params[:code_name])
    self.code = code_to_save
    code_to_save.status = params[:status]
    code_to_save.description = params[:description]
    code_to_save.save
  end
  
end

app/controllers/codelines_controller.rb
class CodelinesController < ApplicationController

  def index
    @codelines = Codeline.paginate(page: params[:page])
    @codelines = Codeline.all
  end

  def show
    @codeline = Codeline.find(params[:id])
  end

  def new

  end

  def create
    @codeline = Codeline.new(params[:codeline])
    if @codeline.save
      flash[:success] = "New Codeline has been saved"
      redirect_to @codeline
    else
      @title = "You have some errors"
      render 'new'
    end
  end

  def edit
    @codeline = Codeline.find(params[:id])
  end

  def update
    @codeline = Codeline.find(params[:id])
    if @codeline.update_attributes(params[:codeline])
       flash[:success] = "Codeline Profile updated"
       redirect_to @codeline
    else
       render 'edit'
    end
  end
end

app/helpers/codelines_helper.rb
module CodelinesHelper
end

app/views/codelines/_fields.html.haml
<fieldset><legend>Enter Contract Details</legend>
= codeline.fields_for :contract do |contract|
  .field
    = contract.label :name, "AuthNum"
    %br/
    = contract.text_field :authnum, :size => 10, :class => "ui-state-default"
  .field
    = contract.label :name, "Start Date"
    %br/
    = contract.text_field :st_date, :size => 12, :class => "ui-state-default"
  .field
    = contract.label :name, "End Date"
    %br/
    = contract.text_field :end_date, :size => 12, :class => "ui-state-default"
    /= link_to_add_fields "Add Codes", contract, :codes
</fieldset>
<fieldset><legend>Enter Client Details</legend>
= codeline.fields_for :client do |client|
  .field
    = client.label :name, "First Name"
    %br/
    = client.text_field :f_name, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "MI"
    %br/
    = client.text_field :mi, :size => 3, :class => "ui-state-default"
  .field
    = client.label :name, "Last Name"
    %br/
    = client.text_field :l_name, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "Birth Date"
    %br/
    = client.text_field :birth_date, :size => 12, :class => "ui-state-default"
  .field
    = client.label :name, "Address1"
    %br/
    = client.text_field :address1, :size => 25, :class => "ui-state-default"
  .field
    = client.label :name, "Address2"
    %br/
    = client.text_field :address2, :size => 25, :class => "ui-state-default"
  .field
    = client.label :name, "City"
    %br/
    = client.text_field :city, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "ZipCode"
    %br/
    = client.text_field :zip_code, :size => 10, :class => "ui-state-default"
  .field
    = client.label :name, "State"
    %br/
    = client.text_field :state, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "MedicareNum"
    %br/
    = client.text_field :medicare_num, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "MedicaidNum"
    %br/
    = client.text_field :medicaid_num, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "MemberNum"
    %br/
    = client.text_field :member_num, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "SocSecCareMgr"
    %br/
    = client.text_field :soc_sec_care_mgr, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "SSCM_Ph"
    %br/
    = client.text_field :sscm_ph, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "NurseCareMgr"
    %br/
    = client.text_field :nurse_care_mgr, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "NCM_Ph"
    %br/
    = client.text_field :ncm_ph, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "EmergencyContact"
    %br/
    = client.text_field :emer_contact, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "EC_Ph"
    %br/
    = client.text_field :ec_ph, :size => 15, :class => "ui-state-default"
  .field
    = client.label :name, "PrimaryCarePhy"
    %br/
    = client.text_field :pri_care_phy, :size => 20, :class => "ui-state-default"
  .field
    = client.label :name, "PCP_Ph"
    %br/
    = client.text_field :pcp_ph, :size => 15, :class => "ui-state-default"
</fieldset>
<fieldset><legend>Enter Billing Code Details</legend>
= codeline.fields_for :code do |code|
  = render 'code_fields', code: code
/  = code.hidden_field :_destroy
/.field
/  = link_to "remove", '#', class: "remove_fields"
/  = link_to_add_fields "Add Codes", code, :code
.field
  = codeline.label :name, "Units Alloc"
  %br/
  = codeline.text_field :units_alloc, :precision => 6, :scale => 2, :size => 10, :class => "ui-state-default"
</fieldset>

app/views/codelines/edit.html.haml
- provide(:title, 'Edit')
%h4 Editing the New Contract
%br/
= form_for(@codeline) do |codeline|
  = render 'form_fields', codeline: codeline
  .actions
  = codeline.submit "Update", class: 'update strong round'

app/views/codelines/index.html.haml
- provide(:title, 'All Codelines')
%h4 All Codelines
%br/
/= will_paginate
%ul.codelines
  = render @codelines
%br/
%br/
/= will_paginate

app/views/codelines/new.html.haml
- provide(:title, 'New Contract')
%h2 New Contract
= form_for(@codeline) do |codeline|
  = render 'shared/codeline_error_messages', object: codeline.object
  = render 'form_fields', codeline: codeline
  .actions
    = codeline.submit "Save", class: 'save strong round'  

app/views/codelines/show.html.haml
- provide(:title, "Codelines")
%h3
	= @codeline.contract.authnum
	= @codeline.client.cli_full_name
	%br/
	%br/
	%ol
		- @codeline.code do |code|
			%li= code.code_name
			%li= code.status
			%li= code.description
	%br/
= link_to 'Edit', edit_codeline_path(@codeline) 
\#{link_to 'Back to Codelines', codelines_path}