config/routes.rb
Tracking::Application.routes.draw do

  get "daily_activities/new"

  root to: 'pages#home'
  
  # Refactored routes to make nearly all resourceful. 

  resources :employees
  resources :clients
  resources :codes
  resources :codelines
  resources :contracts
  resources :sessions, only:  [:new, :create, :destroy]
  
  
  match '/code_list',       to:     'codes#code_list' # Added this route for the autocomplete functionality.
  match '/client_list',     to:     'clients#client_list' # Added this route for the autocomplete functionality.
  match '/get_client_data', to:     'clients#get_client_data' # Added this route for the autocomplete functionality.
  match '/get_code_data',   to:     'codes#get_code_data' # Added this route for the autocomplete functionality.
  match '/employees/:id',   to:     'employees#show', :as => :employee
  match '/newemployee',     to:     'employees#new'
  match '/signin',          to:     'sessions#new'
  match '/signout',         to:     'sessions#destroy', via: :delete
  match '/home',            to:     'pages#home'
  match '/about',           to:     'pages#about'
  match '/contact',         to:     'pages#contact'
  match '/help',            to:     'pages#help'

end

app/models/code.rb
# == Schema Information
#
# Table name: codes
#
#  id          :integer         not null, primary key
#  code_name   :string(255)
#  status      :string(255)
#  description :text
#  created_at  :datetime        not null
#  updated_at  :datetime        not null
#

class Code < ActiveRecord::Base
  has_many :codelines, inverse_of: :code
  has_many :contracts, through: :codelines
  
  attr_accessible :code_name, :status, :description, :meta_status

end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index
    @codes = Code.paginate(page: params[:page])
  end
  
  def code_list
    @codes = Code.order(:code_name).where("code_name like ?", "%#{params[:term]}%")
    render json: @codes.map(&:code_name)
  end    

  def get_code_data
    # raise params[:label]
    code_name = params[:label]
    @code_data = Code.where("code_name like ?", code_name)
    render json: @code_data.first
  end

  def show
    @code = Code.find(params[:id])
  end

  def new
    @code = Code.new
  end

  def create
    @code = Code.new(params[:code])
    if @code.save
      flash[:success] = "New Code has been saved"
      redirect_to @code
    else
      @title = "You have some errors"
      render 'new'
    end
  end

  def edit
    @code = Code.find(param[:id])
  end

  def update
    if @code.update_attributes(params[:code])
       flash[:success] = "Code Profile updated"
       redirect_to @code
    else
       render 'edit'
    end
  end
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_code.html.haml
%li
  %span3
    = link_to(@code_name, codes_path)

app/views/codes/_fields.html.haml
<fieldset><legend>Enter Billing Code Details</legend>
.field
  = code.label :name, "Code Name"
  %br/
  = code.text_field :code_name, :size => 15, :class => "ui-state-default"
.field
  = code.label :name, "Status"
  %br/
  = code.text_field :status, :size => 10, :class => "ui-state-default"
.field
  = code.label :name, "Description"
  %br/
  = code.text_field :description, :size => 25, :class => "ui-state-default"
= code.fields_for :codelines do |codeline|
  .field
    = codeline.label :name, "Units Alloc"
    %br/
    = codeline.text_field :units_alloc, :precision => 6, :scale => 2, :size => 10, :class => "ui-state-default"
</fieldset>
<fieldset><legend>Enter Contract Details</legend>
= code.fields_for :contracts do |contract|
  .field
    = contract.label :name, "AuthNum"
    %br/
    = contract.text_field  :authnum, :size => 10, :class => "ui-state-default"
  .field
    = contract.label :name, "Start Date"
    %br/
    = contract.text_field  :st_date, :size => 12, :class => "ui-state-default"
  .field
    = contract.label :name, "End Date"
    %br/
    = contract.text_field  :end_date, :size => 12, :class => "ui-state-default"
</fieldset>

app/views/codes/edit.html.haml
- provide(:title, 'Edit')
%h4 Edit
#anchor
  = gravatar_for(@employee)
  %a{:href => "http://gravatar.com/emails"} change

app/views/codes/index.html.haml
- provide(:title, 'All codess')
%h4 All codes
= will_paginate
%ul.codes
  = render @codes
= will_paginate

app/views/codes/new.html.haml
- provide(:title, 'Add Codes')
%h2 New Codes
= form_for(@code) do |code|
  =render 'shared/code_error_messages', object: code.object
  =render 'fields', code:  code
  .actions
    = code.submit "Save", class: 'save strong round'

app/views/codes/show.html.haml
- provide(:title, "Codes")
%h3
  %ol
    %li= @code.code_name
    %li= @code.status
    %li= @code.description