config/routes.rb
Tracking::Application.routes.draw do

  get "daily_activities/new"

  root to: 'pages#home'
  
  # Refactored routes to make nearly all resourceful. 

  resources :employees
  resources :clients
  resources :codes
  resources :codelines
  resources :contracts
  resources :sessions, only:  [:new, :create, :destroy]
  
  
  match '/code_list',       to:     'codes#code_list' # Added this route for the autocomplete functionality.
  match '/client_list',     to:     'clients#client_list' # Added this route for the autocomplete functionality.
  match '/get_client_data', to:     'clients#get_client_data' # Added this route for the autocomplete functionality.
  match '/get_code_data',   to:     'codes#get_code_data' # Added this route for the autocomplete functionality.
  match '/employees/:id',   to:     'employees#show', :as => :employee
  match '/newemployee',     to:     'employees#new'
  match '/signin',          to:     'sessions#new'
  match '/signout',         to:     'sessions#destroy', via: :delete
  match '/home',            to:     'pages#home'
  match '/about',           to:     'pages#about'
  match '/contact',         to:     'pages#contact'
  match '/help',            to:     'pages#help'

end

app/views/layouts/_footer.html.erb
<nav class="round">
  <ul>
    <li><strong class="round"><%= link_to "About", about_path %></strong></li>
    <li><strong class="round"><%= link_to "Contact", contact_path %></strong></li>
  </ul>
</nav>
<footer class="round">
</footer>

app/views/layouts/_header.html.erb
<header class="round">
<%= link_to logo, root_path %>
<div id="heading"> TIME AND IT'S COST </div>
<nav class="round">
<ul>
    <li><strong class="round"><%= link_to "Home", root_path %></strong></li>
    <li><strong class="round"><%= link_to "Help", help_path %></strong></li>
    <% if signed_in? && current_employee.admin? %>
      <li><strong class="round"><%= link_to "New Employee", newemployee_path %></strong></li>
      <li><strong class="round"><%= link_to "New Contract", new_contract_path %></strong></li>
      <li><strong class="round"><%= link_to "Employees", employees_path %></strong></li>
      <li><strong class="round"><%= link_to "Profile", current_employee %></strong></li>
      <li><strong class="round"><%= link_to "Settings", edit_employee_path(current_employee) %></li>
      <li><strong class="round"><%= link_to "Sign out", signout_path, method: :delete %></strong></li>
    <% else %>
      <% if signed_in? && current_employee.admin? != true %>
        <li><strong class="round"><%= link_to "Profile", current_employee %></strong></li>
        <li><strong class="round"><%= link_to "Settings", edit_employee_path(current_employee) %></li>
        <li><strong class="round"><%= link_to "Sign out", signout_path, method: :delete %></strong></li>
      <% else %>
      <li><strong class="round"><%= link_to "Sign in", signin_path %></strong></li>
      <% end %>
    <% end %>
  </ul>
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag "application" %>
<%= javascript_include_tag "application" %>
<%= render 'layouts/shim' %>
<%=stylesheet_link_tag 'tableless_css_layout', :media => 'screen' %>

app/views/layouts/application.html.bak.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
      <%= csrf_meta_tag %>
      <%= render 'layouts/stylesheets' %>
  </head>
  <body>
      <div id="page" class="round"><div id="page2" class="round">
        <%= render 'layouts/header' %>
        <section class="round">
        <%- flash.each do |key, value| -%>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <%- end -%>
          <%= yield %>
        </section>
        <%= render 'layouts/footer' %>
      </div></div>
      <div id ="debug">
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
      <%= csrf_meta_tag %>
      <%= render :partial => 'layouts/stylesheets' %>
  </head>
  <body>
      <div id="page" class="round"><div id="page2" class="round">
        <%= render :partial => 'layouts/header' %>
        <section class="round">
        <%- flash.each do |key, value| -%>
          <%= content_tag(:div, value, :class => "flash #{key}") %>
        <%- end -%>
          <%= yield %>
        </section>
        <%= render :partial => 'layouts/footer' %>
      </div></div>
      <div id ="debug">
        <%= debug(params) if Rails.env.development? %>
      </div>
  </body>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= full_title(yield(:title))
    = render 'layouts/stylesheets'
    = csrf_meta_tag
  %body
    #page1.round
      #page2.round
        = render 'layouts/header'
        %section.round
          - flash.each do |key, value|
            = content_tag(:div, value, class: "flash #{key}")
          = yield
        = render 'layouts/footer'
        #debug
          = debug(params) if Rails.env.development?